spring.application.name=vaPaTi
# Puerto

# conection DB
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ApiVaPaTiJava;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=TuContrasenaSegura!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# JWT CONFIG
jwt.secret=your-512-bit-secret-key-should-be-long-and-random
jwt.expiration=3600000
jwt.refresh-expiration=604800000

# Disable stack trace in error responses
server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=false